---
kind: pipeline
name: default

steps:
  - name: npm
    image: node:10-slim
    commands:
      - bash ./ci/npm.sh
    environment:
      NPM_TOKEN:
        from_secret: npm_token

  - name: publish
    image: node:10-slim
    commands:
      - bash ./ci/publish.sh
    when:
      event:
        - pull_request
        - tag

trigger:
  event:
    - pull_request
    - tag
---
kind: signature
hmac: 56e6af0578ce3b2ba14898876f6d4860c57091c89bede149498aa3eeccc0434b

...
